import { PopularWebsite } from '../types/bookmark';

export const POPULAR_WEBSITES: PopularWebsite[] = [
  // --- AI & Generative Tools ---
  {
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    domain: 'aistudio.google.com',
    category: 'AI & Tools',
    iconBg: '#FEF7E0',
    iconColor: '#4285F4',
    initials: 'AI',
    description: 'Fast prototyping with Gemini models and APIs',
  },
  {
    name: 'Google Gemini',
    url: 'https://gemini.google.com',
    domain: 'gemini.google.com',
    category: 'AI & Tools',
    iconBg: '#E8F0FE',
    iconColor: '#1A73E8',
    initials: 'GM',
    description: 'Google direct AI assistant with multimodal reasoning',
  },
  {
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    domain: 'chatgpt.com',
    category: 'AI & Tools',
    iconBg: '#E6F4EA',
    iconColor: '#10A37F',
    initials: 'GPT',
    description: 'Conversational AI and reasoning models by OpenAI',
  },
  {
    name: 'Claude AI',
    url: 'https://claude.ai',
    domain: 'claude.ai',
    category: 'AI & Tools',
    iconBg: '#FEF7E0',
    iconColor: '#D97706',
    initials: 'CL',
    description: 'Anthropic AI assistant for writing, coding, and analysis',
  },
  {
    name: 'Perplexity AI',
    url: 'https://perplexity.ai',
    domain: 'perplexity.ai',
    category: 'AI & Tools',
    iconBg: '#EDE9FE',
    iconColor: '#6366F1',
    initials: 'PX',
    description: 'AI-powered answer engine with real-time web citations',
  },
  {
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    domain: 'deepseek.com',
    category: 'AI & Tools',
    iconBg: '#E0F2FE',
    iconColor: '#0284C7',
    initials: 'DS',
    description: 'Advanced reasoning and open-weight AI models',
  },
  {
    name: 'Cursor',
    url: 'https://cursor.com',
    domain: 'cursor.com',
    category: 'Development',
    iconBg: '#F1EDEC',
    iconColor: '#000000',
    initials: 'CR',
    description: 'The AI-first code editor',
  },
  {
    name: 'Hugging Face',
    url: 'https://huggingface.co',
    domain: 'huggingface.co',
    category: 'AI & Tools',
    iconBg: '#FEF3C7',
    iconColor: '#F59E0B',
    initials: 'HF',
    description: 'The AI community building models, datasets, and apps',
  },
  {
    name: 'Midjourney',
    url: 'https://midjourney.com',
    domain: 'midjourney.com',
    category: 'AI & Tools',
    iconBg: '#1E1B4B',
    iconColor: '#FFFFFF',
    initials: 'MJ',
    description: 'Generative AI art and design platform',
  },
  {
    name: 'v0 by Vercel',
    url: 'https://v0.dev',
    domain: 'v0.dev',
    category: 'Development',
    iconBg: '#000000',
    iconColor: '#FFFFFF',
    initials: 'v0',
    description: 'Generative UI development tool by Vercel',
  },
  {
    name: 'Replit',
    url: 'https://replit.com',
    domain: 'replit.com',
    category: 'Development',
    iconBg: '#FFEDD5',
    iconColor: '#EA580C',
    initials: 'RP',
    description: 'Collaborative browser-based IDE and deployment',
  },
  {
    name: 'Kaggle',
    url: 'https://kaggle.com',
    domain: 'kaggle.com',
    category: 'Science & Math',
    iconBg: '#E0F2FE',
    iconColor: '#0284C7',
    initials: 'KG',
    description: 'Machine learning datasets, competitions, and notebooks',
  },

  // --- Science, Math & Learning ---
  {
    name: 'Wolfram Alpha',
    url: 'https://www.wolframalpha.com',
    domain: 'wolframalpha.com',
    category: 'Science & Math',
    iconBg: '#FEE2E2',
    iconColor: '#DC2626',
    initials: 'WA',
    description: 'Computational intelligence, math solver, and knowledge engine',
  },
  {
    name: 'arXiv',
    url: 'https://arxiv.org',
    domain: 'arxiv.org',
    category: 'Science & Math',
    iconBg: '#F1F5F9',
    iconColor: '#334155',
    initials: 'AX',
    description: 'Open-access scientific papers in Physics, Math, and CS',
  },
  {
    name: 'Overleaf',
    url: 'https://www.overleaf.com',
    domain: 'overleaf.com',
    category: 'Science & Math',
    iconBg: '#DCFCE7',
    iconColor: '#16A34A',
    initials: 'OL',
    description: 'Collaborative cloud LaTeX editor for scientific papers',
  },
  {
    name: 'Desmos Calculator',
    url: 'https://www.desmos.com/calculator',
    domain: 'desmos.com',
    category: 'Science & Math',
    iconBg: '#DCFCE7',
    iconColor: '#15803D',
    initials: 'DM',
    description: 'Advanced graphing calculator and mathematics studio',
  },
  {
    name: 'Physics Stack Exchange',
    url: 'https://physics.stackexchange.com',
    domain: 'physics.stackexchange.com',
    category: 'Science & Math',
    iconBg: '#FEF3C7',
    iconColor: '#B45309',
    initials: 'PH',
    description: 'Q&A for active researchers, academics and physics students',
  },
  {
    name: 'Google Scholar',
    url: 'https://scholar.google.com',
    domain: 'scholar.google.com',
    category: 'Science & Math',
    iconBg: '#DBEAFE',
    iconColor: '#2563EB',
    initials: 'GS',
    description: 'Search scholarly literature and scientific citations',
  },
  {
    name: 'Brilliant',
    url: 'https://brilliant.org',
    domain: 'brilliant.org',
    category: 'Learning',
    iconBg: '#000000',
    iconColor: '#FFFFFF',
    initials: 'BR',
    description: 'Interactive STEM learning courses in math, logic, and physics',
  },
  {
    name: 'Khan Academy',
    url: 'https://www.khanacademy.org',
    domain: 'khanacademy.org',
    category: 'Learning',
    iconBg: '#DCFCE7',
    iconColor: '#15803D',
    initials: 'KA',
    description: 'Free world-class education for anyone, anywhere',
  },
  {
    name: 'Wikipedia',
    url: 'https://wikipedia.org',
    domain: 'wikipedia.org',
    category: 'Learning',
    iconBg: '#F1F5F9',
    iconColor: '#000000',
    initials: 'WK',
    description: 'Free universal encyclopedia',
  },

  // --- Development & Engineering ---
  {
    name: 'GitHub',
    url: 'https://github.com',
    domain: 'github.com',
    category: 'Development',
    iconBg: '#E8F0FE',
    iconColor: '#000000',
    initials: 'GH',
    description: 'Code hosting, git repositories, and open source collaboration',
  },
  {
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    domain: 'stackoverflow.com',
    category: 'Development',
    iconBg: '#FEF7E0',
    iconColor: '#F48024',
    initials: 'SO',
    description: 'Q&A community for software developers',
  },
  {
    name: 'Vercel',
    url: 'https://vercel.com',
    domain: 'vercel.com',
    category: 'Development',
    iconBg: '#E2E2E3',
    iconColor: '#000000',
    initials: 'VC',
    description: 'Frontend cloud platform and hosting',
  },
  {
    name: 'Netlify',
    url: 'https://netlify.com',
    domain: 'netlify.com',
    category: 'Development',
    iconBg: '#CCFBF1',
    iconColor: '#0D9488',
    initials: 'NL',
    description: 'Modern hosting and serverless web platform',
  },
  {
    name: 'Cloudflare',
    url: 'https://cloudflare.com',
    domain: 'cloudflare.com',
    category: 'Development',
    iconBg: '#FFEDD5',
    iconColor: '#F97316',
    initials: 'CF',
    description: 'Web infrastructure, security, and edge hosting',
  },
  {
    name: 'Supabase',
    url: 'https://supabase.com',
    domain: 'supabase.com',
    category: 'Development',
    iconBg: '#DCFCE7',
    iconColor: '#16A34A',
    initials: 'SB',
    description: 'Open source Firebase alternative with PostgreSQL',
  },
  {
    name: 'Firebase',
    url: 'https://firebase.google.com',
    domain: 'firebase.google.com',
    category: 'Development',
    iconBg: '#FEF3C7',
    iconColor: '#D97706',
    initials: 'FB',
    description: 'Google app development platform and Firestore',
  },
  {
    name: 'LeetCode',
    url: 'https://leetcode.com',
    domain: 'leetcode.com',
    category: 'Development',
    iconBg: '#FEF3C7',
    iconColor: '#D97706',
    initials: 'LC',
    description: 'Algorithm practice and technical interview prep',
  },
  {
    name: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    domain: 'developer.mozilla.org',
    category: 'Development',
    iconBg: '#F1F5F9',
    iconColor: '#000000',
    initials: 'MDN',
    description: 'Web documentation for HTML, CSS, and JavaScript',
  },
  {
    name: 'Tailwind CSS',
    url: 'https://tailwindcss.com',
    domain: 'tailwindcss.com',
    category: 'Development',
    iconBg: '#E0F2FE',
    iconColor: '#0284C7',
    initials: 'TW',
    description: 'Utility-first CSS framework for modern web development',
  },
  {
    name: 'React Docs',
    url: 'https://react.dev',
    domain: 'react.dev',
    category: 'Development',
    iconBg: '#E0F2FE',
    iconColor: '#0284C7',
    initials: 'RC',
    description: 'The official documentation for React',
  },
  {
    name: 'Hacker News',
    url: 'https://news.ycombinator.com',
    domain: 'news.ycombinator.com',
    category: 'Development',
    iconBg: '#FFEDD5',
    iconColor: '#EA580C',
    initials: 'HN',
    description: 'Tech and startup news aggregator by Y Combinator',
  },

  // --- Productivity & Workspace ---
  {
    name: 'Notion',
    url: 'https://notion.so',
    domain: 'notion.so',
    category: 'Productivity',
    iconBg: '#F1EDEC',
    iconColor: '#000000',
    initials: 'N',
    description: 'All-in-one workspace for notes, docs, and tasks',
  },
  {
    name: 'Figma',
    url: 'https://figma.com',
    domain: 'figma.com',
    category: 'Design',
    iconBg: '#F3E8FD',
    iconColor: '#F24E1E',
    initials: 'FG',
    description: 'Collaborative UI interface design tool',
  },
  {
    name: 'Linear',
    url: 'https://linear.app',
    domain: 'linear.app',
    category: 'Productivity',
    iconBg: '#EDE9FE',
    iconColor: '#5E6AD2',
    initials: 'LN',
    description: 'Modern issue tracking and project management',
  },
  {
    name: 'Gmail',
    url: 'https://mail.google.com',
    domain: 'mail.google.com',
    category: 'Productivity',
    iconBg: '#FCE8E6',
    iconColor: '#EA4335',
    initials: 'GM',
    description: 'Email service by Google',
  },
  {
    name: 'Google Drive',
    url: 'https://drive.google.com',
    domain: 'drive.google.com',
    category: 'Productivity',
    iconBg: '#FEF7E0',
    iconColor: '#34A853',
    initials: 'GD',
    description: 'Cloud file storage and sharing',
  },
  {
    name: 'Google Docs',
    url: 'https://docs.google.com',
    domain: 'docs.google.com',
    category: 'Productivity',
    iconBg: '#E8F0FE',
    iconColor: '#4285F4',
    initials: 'DOC',
    description: 'Online word processor and document editing',
  },
  {
    name: 'Google Sheets',
    url: 'https://sheets.google.com',
    domain: 'sheets.google.com',
    category: 'Productivity',
    iconBg: '#E6F4EA',
    iconColor: '#0F9D58',
    initials: 'SHT',
    description: 'Cloud spreadsheets and data tables',
  },
  {
    name: 'Google Calendar',
    url: 'https://calendar.google.com',
    domain: 'calendar.google.com',
    category: 'Productivity',
    iconBg: '#DBEAFE',
    iconColor: '#2563EB',
    initials: 'CAL',
    description: 'Time management and scheduling calendar',
  },
  {
    name: 'Canva',
    url: 'https://canva.com',
    domain: 'canva.com',
    category: 'Design',
    iconBg: '#CCFBF1',
    iconColor: '#0D9488',
    initials: 'CV',
    description: 'Graphic design, presentations, and social graphics',
  },
  {
    name: 'Slack',
    url: 'https://slack.com',
    domain: 'slack.com',
    category: 'Productivity',
    iconBg: '#F3E8FD',
    iconColor: '#4A154B',
    initials: 'SK',
    description: 'Team messaging and workspace communications',
  },
  {
    name: 'Discord',
    url: 'https://discord.com',
    domain: 'discord.com',
    category: 'Community',
    iconBg: '#EDE9FE',
    iconColor: '#5865F2',
    initials: 'DC',
    description: 'Voice, video, and community chat channels',
  },

  // --- Media, Music & Streaming ---
  {
    name: 'YouTube',
    url: 'https://youtube.com',
    domain: 'youtube.com',
    category: 'Media',
    iconBg: '#FCE8E6',
    iconColor: '#FF0000',
    initials: 'YT',
    description: 'Video sharing, tutorials, and streaming platform',
  },
  {
    name: 'Spotify',
    url: 'https://spotify.com',
    domain: 'spotify.com',
    category: 'Media',
    iconBg: '#E6F4EA',
    iconColor: '#1DB954',
    initials: 'SP',
    description: 'Music, lo-fi beats, and podcast streaming',
  },
  {
    name: 'Twitch',
    url: 'https://twitch.tv',
    domain: 'twitch.tv',
    category: 'Media',
    iconBg: '#F3E8FD',
    iconColor: '#9146FF',
    initials: 'TW',
    description: 'Live coding, gaming, and creative streaming',
  },
  {
    name: 'Netflix',
    url: 'https://netflix.com',
    domain: 'netflix.com',
    category: 'Media',
    iconBg: '#000000',
    iconColor: '#E50914',
    initials: 'NF',
    description: 'Movies, TV shows, and series streaming',
  },

  // --- Social & Community ---
  {
    name: 'Reddit',
    url: 'https://reddit.com',
    domain: 'reddit.com',
    category: 'Social',
    iconBg: '#FEEFC3',
    iconColor: '#FF4500',
    initials: 'RD',
    description: 'Discussions, tech forums, and internet communities',
  },
  {
    name: 'X / Twitter',
    url: 'https://x.com',
    domain: 'x.com',
    category: 'Social',
    iconBg: '#E2E2E3',
    iconColor: '#000000',
    initials: 'X',
    description: 'Real-time news, tech announcements, and social discourse',
  },
  {
    name: 'LinkedIn',
    url: 'https://linkedin.com',
    domain: 'linkedin.com',
    category: 'Social',
    iconBg: '#E8F0FE',
    iconColor: '#0A66C2',
    initials: 'IN',
    description: 'Professional career network and job opportunities',
  },
  {
    name: 'WhatsApp Web',
    url: 'https://web.whatsapp.com',
    domain: 'web.whatsapp.com',
    category: 'Social',
    iconBg: '#DCFCE7',
    iconColor: '#16A34A',
    initials: 'WA',
    description: 'Instant web messaging and calls',
  },
  {
    name: 'Telegram Web',
    url: 'https://web.telegram.org',
    domain: 'web.telegram.org',
    category: 'Social',
    iconBg: '#E0F2FE',
    iconColor: '#0284C7',
    initials: 'TG',
    description: 'Fast and secure cloud-based messaging',
  },

  // --- Search & Shopping ---
  {
    name: 'Google',
    url: 'https://google.com',
    domain: 'google.com',
    category: 'Search',
    iconBg: '#FEF7E0',
    iconColor: '#4285F4',
    initials: 'G',
    description: 'Search engine and web discovery',
  },
  {
    name: 'Amazon',
    url: 'https://amazon.com',
    domain: 'amazon.com',
    category: 'Shopping',
    iconBg: '#FEF7E0',
    iconColor: '#FF9900',
    initials: 'AZ',
    description: 'Online marketplace and shopping',
  },
];

export function findMatchingWebsites(query: string): PopularWebsite[] {
  if (!query || !query.trim()) {
    return POPULAR_WEBSITES.slice(0, 12);
  }

  const q = query.toLowerCase().trim();
  const tokens = q.split(/\s+/).filter(Boolean);

  // Exact / Multi-token fuzzy match
  return POPULAR_WEBSITES.filter(site => {
    const target = `${site.name} ${site.domain} ${site.category} ${site.description || ''}`.toLowerCase();
    return tokens.every(token => target.includes(token));
  });
}
