import { PopularWebsite } from '../types/bookmark';

export const POPULAR_WEBSITES: PopularWebsite[] = [
  {
    name: 'GitHub',
    url: 'https://github.com',
    domain: 'github.com',
    category: 'Development',
    iconBg: '#E8F0FE',
    iconColor: '#000000',
    initials: 'GH',
    description: 'Code hosting, git repositories, and open source collaboration',
  },
  {
    name: 'YouTube',
    url: 'https://youtube.com',
    domain: 'youtube.com',
    category: 'Media',
    iconBg: '#FCE8E6',
    iconColor: '#FF0000',
    initials: 'YT',
    description: 'Video sharing and streaming platform',
  },
  {
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    domain: 'chatgpt.com',
    category: 'AI',
    iconBg: '#E6F4EA',
    iconColor: '#10A37F',
    initials: 'GPT',
    description: 'Conversational AI and assistant by OpenAI',
  },
  {
    name: 'Google',
    url: 'https://google.com',
    domain: 'google.com',
    category: 'Search',
    iconBg: '#FEF7E0',
    iconColor: '#4285F4',
    initials: 'G',
    description: 'Search engine and Google workspace services',
  },
  {
    name: 'Spotify',
    url: 'https://spotify.com',
    domain: 'spotify.com',
    category: 'Media',
    iconBg: '#E6F4EA',
    iconColor: '#1DB954',
    initials: 'SP',
    description: 'Music and podcast streaming service',
  },
  {
    name: 'Reddit',
    url: 'https://reddit.com',
    domain: 'reddit.com',
    category: 'Community',
    iconBg: '#FEEFC3',
    iconColor: '#FF4500',
    initials: 'RD',
    description: 'Community discussions, news, and memes',
  },
  {
    name: 'Gmail',
    url: 'https://mail.google.com',
    domain: 'mail.google.com',
    category: 'Productivity',
    iconBg: '#FCE8E6',
    iconColor: '#EA4335',
    initials: 'GM',
    description: 'Email by Google',
  },
  {
    name: 'Figma',
    url: 'https://figma.com',
    domain: 'figma.com',
    category: 'Design',
    iconBg: '#F3E8FD',
    iconColor: '#F24E1E',
    initials: 'FG',
    description: 'Collaborative interface design tool',
  },
  {
    name: 'Notion',
    url: 'https://notion.so',
    domain: 'notion.so',
    category: 'Productivity',
    iconBg: '#F1EDEC',
    iconColor: '#000000',
    initials: 'N',
    description: 'All-in-one workspace for notes and docs',
  },
  {
    name: 'Claude',
    url: 'https://claude.ai',
    domain: 'claude.ai',
    category: 'AI',
    iconBg: '#FEF7E0',
    iconColor: '#D97706',
    initials: 'CL',
    description: 'AI assistant by Anthropic',
  },
  {
    name: 'Discord',
    url: 'https://discord.com',
    domain: 'discord.com',
    category: 'Community',
    iconBg: '#EDE9FE',
    iconColor: '#5865F2',
    initials: 'DC',
    description: 'Voice, video, and text communication service',
  },
  {
    name: 'X / Twitter',
    url: 'https://x.com',
    domain: 'x.com',
    category: 'Social',
    iconBg: '#E2E2E3',
    iconColor: '#000000',
    initials: 'X',
    description: 'Real-time social media and news',
  },
  {
    name: 'Linear',
    url: 'https://linear.app',
    domain: 'linear.app',
    category: 'Productivity',
    iconBg: '#EDE9FE',
    iconColor: '#5E6AD2',
    initials: 'LN',
    description: 'Issue tracking and project management',
  },
  {
    name: 'Vercel',
    url: 'https://vercel.com',
    domain: 'vercel.com',
    category: 'Development',
    iconBg: '#E2E2E3',
    iconColor: '#000000',
    initials: 'VC',
    description: 'Frontend cloud platform and hosting',
  },
  {
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    domain: 'stackoverflow.com',
    category: 'Development',
    iconBg: '#FEF7E0',
    iconColor: '#F48024',
    initials: 'SO',
    description: 'Q&A community for developers',
  },
  {
    name: 'Twitch',
    url: 'https://twitch.tv',
    domain: 'twitch.tv',
    category: 'Media',
    iconBg: '#F3E8FD',
    iconColor: '#9146FF',
    initials: 'TW',
    description: 'Live video game and creative streaming',
  },
  {
    name: 'LinkedIn',
    url: 'https://linkedin.com',
    domain: 'linkedin.com',
    category: 'Social',
    iconBg: '#E8F0FE',
    iconColor: '#0A66C2',
    initials: 'IN',
    description: 'Professional networking and jobs',
  },
  {
    name: 'Amazon',
    url: 'https://amazon.com',
    domain: 'amazon.com',
    category: 'Shopping',
    iconBg: '#FEF7E0',
    iconColor: '#FF9900',
    initials: 'AZ',
    description: 'Online shopping and e-commerce',
  }
];

export function findMatchingWebsites(query: string): PopularWebsite[] {
  if (!query || !query.trim()) return POPULAR_WEBSITES.slice(0, 8);
  const q = query.toLowerCase().trim();
  return POPULAR_WEBSITES.filter(site =>
    site.name.toLowerCase().includes(q) ||
    site.domain.toLowerCase().includes(q) ||
    site.category.toLowerCase().includes(q) ||
    (site.description && site.description.toLowerCase().includes(q))
  );
}
